name          'gdsoperations-goenv'
version       '0.0.4'
source        'https://github.com/gds-operations/puppet-goenv'
author        'Government Digital Service'
license       'MIT'
summary       'System wide goenv'
project_page  'https://github.com/gds-operations/puppet-goenv'
